apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS items (
        id UUID PRIMARY KEY DEFAULT uuidv4(),
        created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
    -- On insère deux lignes par défaut pour le test initial
    INSERT INTO items DEFAULT VALUES;
    INSERT INTO items DEFAULT VALUES;
